# Generated by Django 5.2.7 on 2025-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectibles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitterPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500)),
                ("post_id", models.CharField(max_length=30, unique=True)),
                ("author_name", models.CharField(max_length=100)),
                ("author_handle", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "twitter_posts",
            },
        ),
    ]
