# Generated by Django 5.2.7 on 2025-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectibles", "0002_twitterpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArxivPaper",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300)),
                ("arxiv_id", models.CharField(max_length=50, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("authors", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "db_table": "arxiv_papers",
            },
        ),
        migrations.CreateModel(
            name="GithubRepo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=200, unique=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=50)),
                ("homepage", models.URLField(blank=True)),
            ],
            options={
                "db_table": "github_repos",
            },
        ),
    ]
