# Generated by Django 5.2.7 on 2025-12-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectibles", "0003_arxivpaper_githubrepo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "links",
            },
        ),
    ]
